name: "CloudNova Infra // Docs"

on:
  workflow_dispatch:
    
  workflow_run:
    workflows: [CloudNova Infra // CI]
    types: [completed]
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: main

      - name: Render terraform docs inside the README.md
        uses: terraform-docs/gh-actions@6de6da0cefcc6b4b7a5cbea4d79d97060733093c # v1.4.1
        with:
          working-dir: .
          config-file: .terraform-docs.yml
          git-commit-message: "docs(terraform): generated documentation"
          git-push: "true"
